package mx.udg.cucea.interfazgrafica;

import javax.swing.JFrame;

public class Menu extends javax.swing.JFrame {
    // Variables
    private VentanaCC vcc = new VentanaCC();
    
    // Método constructor
    public Menu() {
        initComponents();
        
        // Establecemos el título de la ventana
        setTitle("Menú");
        
        // Establecemos la posición incial de la ventana
        setLocationRelativeTo(null);
        
        // Establecemos que el programa termine cuando se cierre la ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    // Métodos getters
    public VentanaCC getVcc() {
        return vcc;
    }

    // Métodos setters
    public void setVcc(VentanaCC vcc) {
        this.vcc = vcc;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCuentaCorriente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        btnCuentaBancaria1 = new javax.swing.JButton();
        btnCuentaDeAhorros1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 500, 561));
        setMinimumSize(new java.awt.Dimension(425, 518));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(425, 518));
        jPanel1.setMinimumSize(new java.awt.Dimension(425, 518));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elige una opción");

        btnCuentaCorriente.setBackground(java.awt.Color.darkGray);
        btnCuentaCorriente.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnCuentaCorriente.setForeground(new java.awt.Color(204, 204, 204));
        btnCuentaCorriente.setText("Cuenta Corriente");
        btnCuentaCorriente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaCorrienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Banco App");

        btnSalir1.setBackground(java.awt.Color.darkGray);
        btnSalir1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir1.setText("Salir");
        btnSalir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnCuentaBancaria1.setBackground(java.awt.Color.darkGray);
        btnCuentaBancaria1.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnCuentaBancaria1.setForeground(new java.awt.Color(204, 204, 204));
        btnCuentaBancaria1.setText("Cuenta bancaria");
        btnCuentaBancaria1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCuentaBancaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaBancaria1ActionPerformed(evt);
            }
        });

        btnCuentaDeAhorros1.setBackground(java.awt.Color.darkGray);
        btnCuentaDeAhorros1.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnCuentaDeAhorros1.setForeground(new java.awt.Color(204, 204, 204));
        btnCuentaDeAhorros1.setText("Cuenta de Ahorros");
        btnCuentaDeAhorros1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCuentaDeAhorros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaDeAhorros1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCuentaBancaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCuentaDeAhorros1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnCuentaBancaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCuentaDeAhorros1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Botón para cambiar a la ventana de la cuenta corriente
    private void btnCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaCorrienteActionPerformed
        vcc.setM1(this); // Incializamos la ventana cuenta corriente
        vcc.setVisible(true); // Hacemos visible la ventana cuenta corriente
        this.setVisible(false); // Ocultamos el menú
    }//GEN-LAST:event_btnCuentaCorrienteActionPerformed

    // Boton para salir del programa
    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnCuentaBancaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaBancaria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuentaBancaria1ActionPerformed

    private void btnCuentaDeAhorros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaDeAhorros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuentaDeAhorros1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuentaBancaria1;
    private javax.swing.JButton btnCuentaCorriente;
    private javax.swing.JButton btnCuentaDeAhorros1;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
} // Clase Ventana
